suppressMessages(library(limma))
setwd("J:/limma")

GSE106279<-read.csv("GSE106279_array_matrix_averaged.csv")
rownames(GSE106279)<-GSE106279[,1]
l.data<-GSE106279[,-1]
group_list<-rep(c("stable","progress"),times=c(3,3))  
design <- model.matrix(~0+factor(group_list))
colnames(design)=levels(factor(group_list))
rownames(design)=colnames(l.data)
contrast.matrix<-makeContrasts(progress-stable,levels = design)
fit <- lmFit(l.data,design)                                        
fit2 <- contrasts.fit(fit, contrast.matrix) 
fit2 <- eBayes(fit2)                                               
tempOutput = topTable(fit2, coef=1, n=Inf)                         
nrDEG = na.omit(tempOutput) 
write.csv(nrDEG,"GSE106279 PR8-A549 limma DEG.csv")

GSE71766<-read.csv("GSE71766_array_matrix_averaged.csv")
rownames(GSE71766)<-GSE71766[,1]
l.data<-GSE71766[,-1]
group_list<-rep(c("stable","progress"),times=c(5,5)) 
design <- model.matrix(~0+factor(group_list))
colnames(design)=levels(factor(group_list))
rownames(design)=colnames(l.data)
contrast.matrix<-makeContrasts(progress-stable,levels = design)
fit <- lmFit(l.data,design)                                         
fit2 <- contrasts.fit(fit, contrast.matrix) 
fit2 <- eBayes(fit2)                                               
tempOutput = topTable(fit2, coef=1, n=Inf)                         
nrDEG = na.omit(tempOutput) 
write.csv(nrDEG,"GSE71766 WSN-BEAS2B limma DEG.csv")

GSE37571<-read.csv("GSE37571_array_matrix_averaged.csv")
rownames(GSE37571)<-GSE37571[,1]
l.data<-GSE37571[,-1]
group_list<-rep(c("stable","progress"),times=c(3,3)) 
design <- model.matrix(~0+factor(group_list))
colnames(design)=levels(factor(group_list))
rownames(design)=colnames(l.data)
contrast.matrix<-makeContrasts(progress-stable,levels = design)
fit <- lmFit(l.data,design)                                        
fit2 <- contrasts.fit(fit, contrast.matrix) 
fit2 <- eBayes(fit2)                                               
tempOutput = topTable(fit2, coef=1, n=Inf)                        
nrDEG = na.omit(tempOutput) 
write.csv(nrDEG,"GSE37571 CA04-Calu3 limma DEG.csv")

BiocManager::install(c("beadarray", "beadarrayExampleData"))
library(beadarray)
require(beadarrayExampleData)
library(preprocessCore)
GSE32139<-read.csv("GSE32139_array_matrix_averaged.csv")
rownames(GSE32139)<-GSE32139[,1]
l.data<-log2(GSE32139[,-1])
l.data<-normalize.quantiles(as.matrix(l.data))
l.data<-data.frame(l.data)
rownames(l.data)<-rownames(GSE32139)
colnames(l.data)<-colnames(GSE32139[,-1])
group_list<-rep(c("stable","progress"),times=c(2,4))
design <- model.matrix(~0+factor(group_list))
colnames(design)=levels(factor(group_list))
rownames(design)=colnames(l.data)
contrast.matrix<-makeContrasts(progress-stable,levels = design)
fit <- lmFit(l.data,design)                                         
fit2 <- contrasts.fit(fit, contrast.matrix) 
fit2 <- eBayes(fit2)                                                
tempOutput = topTable(fit2, coef=1, n=Inf)                         
nrDEG = na.omit(tempOutput) 
write.csv(nrDEG,"不分病毒株_仅数据集内比对/GSE32139 Udorn-hAEC limma DEG.csv")

GSE61517<-read.csv("GSE61517_count_summed.csv")
rownames(GSE61517)<-GSE61517[,1]
l.data<-GSE61517[,-1]
group_list<-c("stable","stable","stable","B","B","B","P","P","P","U","U","U") 
design <- model.matrix(~0+factor(group_list))
colnames(design)=levels(factor(group_list))
rownames(design)=colnames(l.data)
contrast.matrix<-makeContrasts(B-stable,P-stable,U-stable,levels = design)    
y = voom(l.data,design, plot = T)
fit <- lmFit(y,design)                                         
fit2 <- contrasts.fit(fit, contrast.matrix) 
fit2 <- eBayes(fit2) 
tempOutputB = topTable(fit2, coef=1, n=Inf)                         
nrDEGB = na.omit(tempOutputB) 
tempOutputP = topTable(fit2, coef=2, n=Inf)                         
nrDEGP = na.omit(tempOutputP) 
tempOutputU = topTable(fit2, coef=3, n=Inf)                         
nrDEGU = na.omit(tempOutputU) 
write.csv(nrDEGB,"GSE61517 Brisbane-BEAS2B limma DEG.csv")
write.csv(nrDEGP,"GSE61517 Perth-BEAS2B limma DEG.csv")
write.csv(nrDEGU,"GSE61517 Udorn-BEAS2B limma DEG.csv")

GSE104168<-read.csv("GSE104168 STAR HTseq count trimmed-stranded F.csv")
rownames(GSE104168)<-GSE104168[,1]
l.data<-GSE104168[,-1]
group_list<-c("stable","stable","stable","H3N2","H3N2","H3N2","H1N1","H1N1","H1N1") 
design <- model.matrix(~0+factor(group_list))
colnames(design)=levels(factor(group_list))
rownames(design)=colnames(l.data)
contrast.matrix<-makeContrasts(H3N2-stable,H1N1-stable,levels = design) 
y = voom(l.data,design, plot = T)
fit <- lmFit(y,design)                                       
fit2 <- contrasts.fit(fit, contrast.matrix) 
fit2 <- eBayes(fit2) 
tempOutputH3N2 = topTable(fit2, coef=1, n=Inf)                     
nrDEGH3N2 = na.omit(tempOutputH3N2) 
tempOutputH1N1 = topTable(fit2, coef=2, n=Inf)                   
nrDEGH1N1 = na.omit(tempOutputH1N1) 
write.csv(nrDEGH3N2,"GSE104168 NY238-A549 limma DEG.csv")
write.csv(nrDEGH1N1,"GSE104168 NPR8-A549 limma DEG.csv")
